---
title       : Text Predictor
subtitle    : Coursera, Data Science, Capstone Project
author      : Patrick Charles
job         : interval software engineering
framework   : revealjs
highlighter : highlight.js  # {highlight.js, prettify, highlight}
hitheme     : tomorrow      # 
widgets     : []            # {mathjax, quiz, bootstrap}
mode        : selfcontained # {standalone, draft}
knit        : slidify::knit2slides

--- .class #id 

## Text Prediction

[Patrick Charles](http://pchuck.net)  
2015.07.21  
Coursera/Johns Hopkins Data Science Series  
Capstone Project

--- .class #id 

## Background

A body of [sample texts](https://d396qusza40orc.cloudfront.net/dsscapstone/dataset/Coursera-SwiftKey.zip) consisting of ~4M documents including tweets, news articles and blog posts are loaded and exploratory analysis performed. Sets of n-grams are extracted from the corpus, predictive algororithms built, and various approaches for improving predictive accuracy refined.

--- .class #id 

## Optimization

* 4M corpus -> 1M documents via random sampling 
* 1M documents transformed and reduced
* Iterative process of analysis, optimization and perf testing
* Document-term matrices generated with {1-5}-ngrams 
* n-grams organized by frequency of occurrence in corpus
* Least common n-grams pruned/dropped for final model..
    * 18,936 words occurring more than 10x
    * 199,966 2-grams w/ frequency > 3x
    * 150,489 3-grams w/ frequency > 3x
    * 139,984 4-grams w/ frequency > 2x
    * 43,024 5-grams w/ frequency > 2x
    * 9.1MB total, compressed

--- .class #id 

## Prediction Algorithm

* Capture input text, including all preceding words in the phrase
* Iteratively traverse n-grams (longest to shortest) for matches
* On match(es), use the longest, most common, n-gram
* Last word in the matching n-gram is the predicted next word
* If no match in {5, 4, 3, 2}-grams, resort to randomly selecting a most frequently occurring 1-gram (e.g. common word)

--- .class #id

## Performance
* **15%** Accuracy (using only first, top-ranked response)
* **22%** Accuracy (selecting from top-5 ranked responses)
* Mean Response Time: **250ms**
* Memory: **9MB** compressed, **104MB** in-memory

<br>
## Application

[text-predictor](https://pchuck.shinyapps.io/text-predictor)
interactively performs word/phrase completion!

<br>

* [github repository](http://github.com/pchuck/coursera-ds-capstone) - algorithms/optimizations
* [milestone 1](http://rpubs.com/pchuck/dsc_milestone) - cursory analysis
* [rpubs final report](http://rpubs.com/pchuck/text-predictor) - final analysis

